name: Cloudflare Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build
        run: yarn && yarn build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
